-- Schema creation script for Product catalog
-- This file is referenced by persistence.xml for schema generation

-- Note: This is a placeholder file. 
-- The actual schema is auto-generated by JPA using @Entity annotations.
-- You can add custom DDL statements here if needed.
