INSERT INTO Product (name, description, price) VALUES ('iPhone', 'Apple iPhone 15', 999.99)
INSERT INTO Product (name, description, price) VALUES ('MacBook', 'Apple MacBook Air', 1299.0)
INSERT INTO Product (name, description, price) VALUES ('iPad', 'Apple iPad Pro', 799.99)
INSERT INTO Product (name, description, price) VALUES ('AirPods', 'Apple AirPods Pro', 249.99)
INSERT INTO Product (name, description, price) VALUES ('Apple Watch', 'Apple Watch Series 8', 399.99)
